# Generated by Django 2.0 on 2018-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbl_latitude', models.FloatField()),
                ('dbl_longitude', models.FloatField()),
                ('txt_address', models.TextField()),
                ('dat_created', models.DateField()),
            ],
        ),
    ]
